name: uudi_card_plugin
description: package for uudi aplication.
version: 1.1.1
author: UUDI
homepage: https://github.com/gianlucagodoy/uudi_card_plugin.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.0.1
  intl: ^0.17.0
  provider: ^5.0.0
  flutter_mobx: ^2.0.0
  cupertino_icons: ^0.1.3
  flutter_masked_text: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  mobx_codegen: ^2.0.1+3  


flutter:
  uses-material-design: true
  assets:
    - assets/
 