name: uudi_card_plugin
description: package for uudi aplication.
version: 0.0.1
author: UUDI
homepage: https://github.com/gianlucagodoy/uudi_card_plugin.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^1.1.1
  intl: ^0.17.0
  provider: ^4.0.4
  flutter_mobx: ^1.1.0
  cupertino_icons: ^0.1.2
  flutter_masked_text: ^0.8.0
  mobx_codegen: ^1.0.3  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1  


flutter:
  uses-material-design: true
  assets:
    - assets/
 